"""AI专项质量规则 - 调试残留与AI生成标记
从 ai_specific_rules.py 拆分而来，包含调试代码残留和AI生成标记检测（AI-SPEC-03, AI-SPEC-04）
"""

"""
智能质检 - P0 特有问题检测规则 (v3.4 AST增强版)
最具差异化的AI增强检测能力，传统Linter难以覆盖的问题

v3.4 改进: JS检查全部改用AST解析(@babel/parser)，消除正则误报。
           Python检查保持原有ast模块实现。

AI-SPEC-01: 幻觉依赖检测 - import的包在pypi/npm不存在（AI瞎编的包名）
AI-SPEC-02: 占位符残留 - TODO: implement、空函数体等AI生成的占位代码
AI-SPEC-03: 调试代码残留 - console.log、print()、debugger 留在生产代码
AI-SPEC-04: AI生成标记 - // Generated by ChatGPT 这类来源标注
"""

import re
import os
import ast
import json
import time as _time
import urllib.request
import urllib.error
from typing import List, Dict, Any, Set

# 从 hallucination.py 导入共享工具函数
try:
    from .hallucination import _is_vendored_js_file, _get_ast_analyzer
except ImportError:
    def _is_vendored_js_file(fpath, rel, content):
        return False
    def _get_ast_analyzer():
        return None

# 尝试导入AST分析器（延迟初始化，避免import时阻塞）
_ast_analyzer = None
_ast_available = None  # None = 未检查，True/False = 已检查


# ===== AI-SPEC-03 调试代码残留 =====
def check_ai_spec_03_debug_remnants(context) -> List[Dict]:
    """AI-SPEC-03 调试代码残留检测
    AI生成代码常把console.log/print()/debugger留在生产代码中
    误报控制：区分调试输出(console.log/debug)和正常日志(console.error/warn)；
              排除CLI工具脚本和入口文件；排除__main__块内的print
    
    v3.4: JS console.log/debug检测改用AST，精准识别console成员调用，
         不再误匹配字符串中的console.log文本。
    """
    results = []
    
    py_files = [f for f in context.get_filtered_files("performance")
                if f.endswith(".py") and os.path.basename(f) != "__init__.py"]
    js_files = [f for f in context.get_filtered_files("performance") if f.endswith((".js", ".ts", ".jsx", ".tsx"))]
    
    if not py_files and not js_files:
        return results
    
    all_issues = []
    
    def _is_cli_script_py(fpath: str, content: str) -> bool:
        """判断是否为CLI工具脚本（允许print）"""
        basename = os.path.basename(fpath).lower()
        rel = os.path.relpath(fpath, context.project_path or context.backend_path or ".")
        rel_parts = rel.lower().replace('\\', '/').split('/')
        
        cli_dirs = {'scripts', 'tools', 'utils', 'bin', 'cli', 'commands', 'cmd'}
        if any(d in rel_parts for d in cli_dirs):
            return True
        
        cli_name_markers = ['cli', 'script', 'tool', 'command', 'main', 'entry',
                           'update_', 'verify_', 'check_', 'gen_', 'build_',
                           'migrate', 'setup', 'install', 'deploy']
        if any(marker in basename for marker in cli_name_markers):
            return True
        
        if re.search(r'import\s+(argparse|click|fire|typer)', content):
            return True
        
        first_line = content.split('\n', 1)[0] if content else ''
        if first_line.startswith('#!') and 'python' in first_line:
            if len(rel_parts) <= 2:
                return True
        
        return False
    
    def _find_print_in_main_block(tree) -> set:
        """找到if __name__ == '__main__'块内的所有print调用行号"""
        main_lines = set()
        
        for node in ast.walk(tree):
            if not isinstance(node, ast.If):
                continue
            test = node.test
            if isinstance(test, ast.Compare) and len(test.ops) == 1 and isinstance(test.ops[0], ast.Eq):
                left = test.left
                if isinstance(left, ast.Name) and left.id == '__name__':
                    for sub_node in ast.walk(node):
                        if isinstance(sub_node, ast.Call):
                            if isinstance(sub_node.func, ast.Name) and sub_node.func.id == 'print':
                                main_lines.add(sub_node.lineno)
        
        return main_lines
    
    # ===== Python: print() 残留（用AST，保持原有实现）=====
    for fpath in py_files:
        content = context.safe_read(fpath)
        if not content:
            continue
        
        lines = content.split('\n')
        rel = os.path.relpath(fpath, context.project_path or context.backend_path or ".")
        basename = os.path.basename(fpath)
        
        if _is_cli_script_py(fpath, content):
            continue
        
        if basename.startswith('test_') or 'test' in basename.lower():
            continue
        
        if any(x in basename.lower() for x in ['example', 'demo', 'sample']):
            continue
        
        try:
            tree = context.parse_ast(fpath)
            if tree is None:
                continue
            main_print_lines = _find_print_in_main_block(tree)
            
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                if not isinstance(node.func, ast.Name) or node.func.id != 'print':
                    continue
                
                lineno = node.lineno
                
                if lineno in main_print_lines:
                    continue
                
                line_content = lines[lineno - 1].strip() if lineno - 1 < len(lines) else ""
                
                all_issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': lineno,
                    'desc': 'print()调试残留',
                    'snippet': line_content[:100],
                    'lang': 'python',
                })
        except SyntaxError:
            continue
    
    # ===== JS/TS: console.log / console.debug / debugger =====
    for fpath in js_files:
        content = context.safe_read(fpath)
        if not content:
            continue
        
        lines = content.split('\n')
        rel = os.path.relpath(fpath, context.project_path or context.backend_path or ".")
        basename = os.path.basename(fpath)
        
        if any(x in basename.lower() for x in ['.test.', '.spec.', 'test.']):
            continue
        
        if basename in ('vite.config.js', 'vite.config.ts', 'webpack.config.js',
                        'next.config.js', 'vue.config.js', 'jest.config.js',
                        'eslint.config.js', 'prettier.config.js'):
            continue
        
        if any(x in basename.lower() for x in ['example', 'demo', 'sample']):
            continue
        
        if _is_vendored_js_file(fpath, rel, content):
            continue
        
        _analyzer = _get_ast_analyzer()
        if _analyzer:
            # ===== v3.4 AST模式: 精准识别console成员调用 =====
            ast_console = _analyzer.get_js_console_calls(fpath)
            if ast_console is not None:
                for cc in ast_console:
                    method = cc.get("method", "")
                    line_num = cc.get("line", 0)
                    
                    # 只有console.log/debug/trace算调试残留
                    # console.error/warn/info是正常日志
                    if method not in ('log', 'debug', 'trace'):
                        continue
                    
                    line_content = lines[line_num - 1].strip() if line_num - 1 < len(lines) else ""
                    
                    # 跳过注释行
                    if line_content.startswith('//') or line_content.startswith('/*'):
                        continue
                    
                    # 检查是否在注释中（行内注释）
                    code_part = line_content.split('//')[0]
                    if 'console' not in code_part:
                        continue
                    
                    all_issues.append({
                        'file': fpath,
                        'rel': rel,
                        'line': line_num,
                        'desc': f'console.{method}()调试残留',
                        'snippet': line_content[:100],
                        'lang': 'js',
                    })
                
                # debugger检测仍用正则（AST中debugger是DebuggerStatement，但正则足够简单）
                debugger_pattern = re.compile(r'\bdebugger\s*;?', re.MULTILINE)
                for m in debugger_pattern.finditer(content):
                    line_num = content[:m.start()].count('\n') + 1
                    line_content = lines[line_num - 1].strip() if line_num - 1 < len(lines) else ""
                    
                    if line_content.startswith('//'):
                        continue
                    
                    all_issues.append({
                        'file': fpath,
                        'rel': rel,
                        'line': line_num,
                        'desc': 'debugger语句残留',
                        'snippet': line_content[:100],
                        'lang': 'js',
                    })
                continue
            # AST对该文件不可用，降级到正则
        
        # ===== 正则降级模式 =====
        console_debug_pattern = re.compile(r'console\.(log|debug|trace)\s*\(', re.MULTILINE)
        debugger_pattern = re.compile(r'\bdebugger\s*;?', re.MULTILINE)
        
        for m in console_debug_pattern.finditer(content):
            line_num = content[:m.start()].count('\n') + 1
            line_content = lines[line_num - 1].strip() if line_num - 1 < len(lines) else ""
            
            if line_content.startswith('//') or line_content.startswith('/*'):
                continue
            
            code_part = line_content.split('//')[0]
            if 'console' not in code_part:
                continue
            
            all_issues.append({
                'file': fpath,
                'rel': rel,
                'line': line_num,
                'desc': f'console.{m.group(1)}()调试残留',
                'snippet': line_content[:100],
                'lang': 'js',
            })
        
        for m in debugger_pattern.finditer(content):
            line_num = content[:m.start()].count('\n') + 1
            line_content = lines[line_num - 1].strip() if line_num - 1 < len(lines) else ""
            
            if line_content.startswith('//'):
                continue
            
            all_issues.append({
                'file': fpath,
                'rel': rel,
                'line': line_num,
                'desc': 'debugger语句残留',
                'snippet': line_content[:100],
                'lang': 'js',
            })
    
    if all_issues:
        total = len(all_issues)
        detail_lines = [
            f"{issue['rel']}:{issue['line']} - {issue['desc']}"
            for issue in all_issues[:15]
        ]
        
        results.append({
            'id': 'AI-SPEC-03',
            'name': '调试代码残留',
            'level': 'warning',
            'message': f'发现 {total} 处调试代码残留（print/console.log/debugger）',
            'detail': '\n'.join(detail_lines),
            'file': all_issues[0]['file'] if all_issues else '',
            'line': all_issues[0]['line'] if all_issues else 0,
            'snippet': all_issues[0]['snippet'] if all_issues else '',
            'fix': '删除调试代码，使用日志框架替代print/console.log',
            'category': 'ai_specific',
            'suggestion_code': '// 错误：生产代码中的调试残留\nconsole.log("debug:", data);\ndebugger;\nconsole.log("user info:", userInfo);\n\n// 正确：使用日志框架（或条件日志）\n// 方案1：条件日志（开发环境保留）\nif (__DEV__) {\n  console.log("debug:", data);\n}\n\n// 方案2：统一日志模块\nimport { logger } from "./utils/logger";\nlogger.debug("debug:", data);\nlogger.info("user info:", userInfo);\n\n// Python同理：\n# 错误：print("debug:", data)\n# 正确：import logging; logger = logging.getLogger(__name__); logger.debug("debug: %s", data)',
        })
    
    return results


# ===== AI-SPEC-04 AI生成标记 =====



# ===== AI-SPEC-04 AI生成标记 =====
def check_ai_spec_04_ai_generated_markers(context) -> List[Dict]:
    """AI-SPEC-04 AI生成标记检测
    检测代码中的"Generated by ChatGPT"等AI来源标注
    """
    results = []
    
    all_files = context.find_files([".py", ".js", ".ts", ".jsx", ".tsx", ".html", ".css"])
    if not all_files:
        return results
    
    ai_marker_patterns = [
        (r'Generated by (?:ChatGPT|GPT|AI|Copilot|Claude|Bard)', 'AI生成标注'),
        (r'(?:Created|Written|Generated) with (?:AI|GPT|ChatGPT|Copilot)', 'AI生成标注'),
        (r'由(?:ChatGPT|GPT|AI|人工智能|大模型)(?:生成|编写|创建)', 'AI生成标注'),
        (r'Code generated by (?:AI|GPT|ChatGPT)', 'AI生成标注'),
        (r'AI-assisted code', 'AI辅助编写标注'),
        (r'prompt.*generated|generated.*prompt', 'Prompt生成标注'),
    ]
    
    all_issues = []
    
    for fpath in all_files:
        content = context.safe_read(fpath)
        if not content:
            continue
        
        lines = content.split('\n')
        rel = os.path.relpath(fpath, context.project_path or context.backend_path or ".")
        
        for pat, desc in ai_marker_patterns:
            for m in re.finditer(pat, content, re.IGNORECASE):
                line_num = content[:m.start()].count('\n') + 1
                all_issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': line_num,
                    'desc': desc,
                    'snippet': lines[line_num - 1].strip()[:100] if line_num - 1 < len(lines) else "",
                })
    
    if all_issues:
        total = len(all_issues)
        detail_lines = [
            f"{issue['rel']}:{issue['line']} - {issue['desc']}"
            for issue in all_issues[:10]
        ]
        
        results.append({
            'id': 'AI-SPEC-04',
            'name': 'AI生成标记检测',
            'level': 'info',
            'message': f'发现 {total} 处AI生成代码来源标注',
            'detail': '\n'.join(detail_lines),
            'file': all_issues[0]['file'] if all_issues else '',
            'line': all_issues[0]['line'] if all_issues else 0,
            'snippet': all_issues[0]['snippet'] if all_issues else '',
            'fix': '建议人工Review后移除AI生成标注，确保代码经过质量验证',
            'category': 'ai_specific',
            'suggestion_code': '// 错误：代码中保留AI生成标注\n// Generated by ChatGPT\n// This code was written by AI Assistant\nfunction processData() { ... }\n\n// 正确：移除AI标注，代码应经过人工Review\nfunction processData() { ... }',
        })
    
    return results


# ===== 规则定义列表 =====


# ===== 规则定义列表 =====
RULES = [
    {
        'id': 'AI-SPEC-03',
        'name': '调试代码残留',
        'level': 'problem',
        'category': 'ai_code_check',
        'module_id': 'ai_specific',
        'applicable_types': [],
        'description': '检测print()、console.log、debugger等调试代码残留，JS检测使用AST增强',
        'check': check_ai_spec_03_debug_remnants,
    },
    {
        'id': 'AI-SPEC-04',
        'name': 'AI生成标记检测',
        'level': 'suggestion',
        'category': 'ai_code_check',
        'module_id': 'ai_specific',
        'applicable_types': [],
        'description': '检测"Generated by ChatGPT"等AI生成代码来源标注',
        'check': check_ai_spec_04_ai_generated_markers,
    },
]
