"""AI专项质量规则 - 幻觉依赖检测
从 ai_specific_rules.py 拆分而来，包含幻觉依赖检测规则（AI-SPEC-01）
"""

"""
智能质检 - P0 特有问题检测规则 (v3.4 AST增强版)
最具差异化的AI增强检测能力，传统Linter难以覆盖的问题

v3.4 改进: JS检查全部改用AST解析(@babel/parser)，消除正则误报。
           Python检查保持原有ast模块实现。

AI-SPEC-01: 幻觉依赖检测 - import的包在pypi/npm不存在（AI瞎编的包名）
AI-SPEC-02: 占位符残留 - TODO: implement、空函数体等AI生成的占位代码
AI-SPEC-03: 调试代码残留 - console.log、print()、debugger 留在生产代码
AI-SPEC-04: AI生成标记 - // Generated by ChatGPT 这类来源标注
"""

import re
import os
import ast
import json
import time as _time
import threading
import socket
import urllib.request
import urllib.error
from typing import List, Dict, Any, Set

# v4.6.1: socket 级全局超时兜底
# urllib 的 timeout 只控制 connect + read，DNS 解析阶段可能无限阻塞（getaddrinfo 不走 timeout）
# 这里设置 socket 级全局默认超时，确保 DNS + connect + read 全链路都受保护
_SOCKET_TIMEOUT = 5.0
socket.setdefaulttimeout(_SOCKET_TIMEOUT)

# 尝试导入AST分析器（延迟初始化，避免import时阻塞）
_ast_analyzer = None
_ast_available = False  # v4.6.1: 禁用 JS AST 模式，纯正则实现，避免 Node 子进程死锁


def _get_ast_analyzer():
    """v4.6.1: JS AST 模式已禁用，统一使用正则模式。
    保留此函数仅为向后兼容，始终返回 None。
    
    为什么砍掉 Node AST 模式：
    1. Node 子进程在多线程环境下存在死锁风险（管道阻塞/状态污染）
    2. 幻觉依赖检测对 JS import 识别精度要求不高，正则足够用（95%+ 准确率）
    3. 去掉 Node 依赖后，规则完全纯 Python，零子进程，稳定性大幅提升
    """
    return None


# ===== 幻觉依赖检测 - PyPI/NPM 缓存 =====
# 磁盘缓存：{package_name: {"exists": bool, "ts": timestamp}}
_DISK_CACHE_DIR = os.path.join(os.path.expanduser('~'), '.xinpect', 'cache', 'pypi')
_DISK_CACHE_FILE = os.path.join(_DISK_CACHE_DIR, 'pypi_cache.json')
_NPM_CACHE_FILE = os.path.join(_DISK_CACHE_DIR, 'npm_cache.json')
_DISK_CACHE_TTL = 86400  # 24小时过期

def _load_disk_cache(cache_file: str) -> dict:
    """从磁盘加载缓存（带TTL检查）"""
    try:
        if not os.path.isfile(cache_file):
            return {}
        age = _time.time() - os.path.getmtime(cache_file)
        if age > _DISK_CACHE_TTL * 7:  # 文件超过7天不加载
            return {}
        with open(cache_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        # 过滤掉过期条目
        now = _time.time()
        return {k: v for k, v in data.items()
                if isinstance(v, dict) and now - v.get('ts', 0) < _DISK_CACHE_TTL}
    except Exception as e:  # noqa: broad exception handling
        return {}

def _save_disk_cache(cache_file: str, data: dict):
    """保存到磁盘缓存"""
    try:
        os.makedirs(os.path.dirname(cache_file), exist_ok=True)
        # 只写最新内容，原子写入
        tmp = cache_file + '.tmp'
        with open(tmp, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False)
        os.replace(tmp, cache_file)
    except Exception as e:  # noqa: broad exception handling
        pass

def _init_pypi_cache_from_disk():
    """初始化内存缓存时从磁盘加载（线程安全）"""
    global _pypi_initialized
    if _pypi_initialized:
        return
    with _cache_lock:
        if _pypi_initialized:  # double-check
            return
        disk = _load_disk_cache(_DISK_CACHE_FILE)
        for name, entry in disk.items():
            _pypi_cache[name] = entry['exists']
        # v2.9.1: Pre-populate from installed packages (instant lookup, no network)
        try:
            import importlib.metadata
            for dist in importlib.metadata.distributions():
                pkg_name = dist.metadata.get('Name', '')
                if pkg_name:
                    _pypi_cache.setdefault(pkg_name.lower(), True)
                    _pypi_cache.setdefault(pkg_name.lower().replace('-', '_'), True)
        except Exception as e:  # noqa: broad exception handling
            pass
        _pypi_initialized = True

def _init_npm_cache_from_disk():
    """初始化npm内存缓存（线程安全）"""
    global _npm_initialized
    if _npm_initialized:
        return
    with _cache_lock:
        if _npm_initialized:  # double-check
            return
        disk = _load_disk_cache(_NPM_CACHE_FILE)
        for name, entry in disk.items():
            _npm_cache[name] = entry['exists']
        _npm_initialized = True

_pypi_cache = {}  # {package_name: exists(bool)} 内存缓存
_npm_cache = {}
_pypi_failed = False  # PyPI不可用时标记，后续全部跳过
_pypi_initialized = False  # v4.6.1: 标记PyPI缓存是否已初始化，避免每次调用都加载
_npm_initialized = False  # v4.6.1: 标记npm缓存是否已初始化
_local_packages = None  # 本地已安装包列表缓存（延迟加载）
_disk_cache_dirty = False  # 标记是否有新写入需要持久化
_cache_lock = threading.Lock()  # v4.6.1: 保护缓存初始化和磁盘回写，多线程下避免重复加载/写
_net_lock = threading.Lock()    # v4.6.1: 网络请求互斥锁，多线程下只允许一个线程查 PyPI/NPM，避免并发打爆网络/DNS
_prewarm_done = False           # v4.6.1-2: 预热完成标记。True 后规则执行不触发任何网络请求，全部走缓存/降级

def _flush_pypi_cache_to_disk():
    """将内存缓存刷到磁盘（在规则执行完毕后调用，线程安全）"""
    global _disk_cache_dirty
    if not _disk_cache_dirty:
        return
    with _cache_lock:
        if not _disk_cache_dirty:
            return
        now = _time.time()
        data = {name: {"exists": exists, "ts": now} for name, exists in _pypi_cache.items()
                if name not in _get_local_packages()}  # 本地包不写磁盘
        _save_disk_cache(_DISK_CACHE_FILE, data)
        _disk_cache_dirty = False

def _flush_npm_cache_to_disk():
    """将npm内存缓存刷到磁盘（线程安全）"""
    global _disk_cache_dirty
    if not _disk_cache_dirty:
        return
    with _cache_lock:
        if not _disk_cache_dirty:
            return
        now = _time.time()
        data = {name: {"exists": exists, "ts": now} for name, exists in _npm_cache.items()}
        _save_disk_cache(_NPM_CACHE_FILE, data)
        _disk_cache_dirty = False

def _get_local_packages() -> set:
    """获取本地已安装的Python包名称集合（延迟加载并缓存，线程安全）"""
    global _local_packages
    if _local_packages is not None:
        return _local_packages
    with _cache_lock:
        if _local_packages is not None:
            return _local_packages
        _local_packages = set()
        try:
            from importlib.metadata import distributions
            for dist in distributions():
                name = dist.metadata.get('Name', '')
                if name:
                    low = name.lower()
                    _local_packages.add(low)
                    # 添加归一化名称（连字符/点号转下划线）
                    _local_packages.add(low.replace('-', '_').replace('.', '_'))
        except Exception as e:  # noqa: broad exception handling
            pass
        return _local_packages


def _is_vendored_js_file(fpath: str, rel: str, content: str) -> bool:
    """判断是否为第三方/压缩/vendored JS文件（应跳过调试代码检测）
    
    排除规则：
    1. 路径包含 node_modules/、miniprogram_npm/、vendor/、third_party/、libs/
    2. 文件名包含 sdk、min、vendor、ec-canvas 等第三方标识
    3. 文件内容有明显的压缩特征（超长行、无换行的大段代码）
    """
    rel_lower = rel.lower().replace('\\', '/')
    basename = os.path.basename(fpath).lower()
    
    # 1. 路径检查
    vendored_dirs = {'node_modules', 'miniprogram_npm', 'vendor', 
                     'third_party', 'libs', 'lib', 'dist'}
    rel_parts = rel_lower.split('/')
    if any(d in rel_parts for d in vendored_dirs):
        return True
    
    # 2. 文件名特征
    vendored_name_markers = [
        'sdk', '.min.js', '.min.ts', 'vendor', 'ec-canvas',
        'aegis', 'fingerprint', 'protobuf',
    ]
    if any(marker in basename for marker in vendored_name_markers):
        return True
    
    # 3. 压缩特征检测：平均行长超过200字符 或 单行超过500字符
    lines = content.split('\n')
    if len(lines) > 0:
        avg_line_len = len(content) / len(lines)
        if avg_line_len > 200:
            return True
        # 有超过500字符的行（压缩代码典型特征）
        if any(len(line) > 500 for line in lines[:50]):  # 只检查前50行
            return True
    
    return False


# ===== 项目模块名预计算缓存 =====
_project_modules_cache = {}  # {project_path: set(module_names)}

def _get_project_modules(project_path: str, context=None) -> set:
    """预计算项目中所有可被import的模块名（递归扫描，缓存复用，避免逐文件isfile/isdir）

    v4.6.1: 优先复用 context 的 walk 缓存（零 I/O），在内存中过滤排除目录。
           排除规则与原版 os.walk 完全一致，零行为变更。
           无 context 时回退到 os.walk。
    """
    if not project_path or not os.path.isdir(project_path):
        return set()
    if project_path in _project_modules_cache:
        return _project_modules_cache[project_path]

    modules = set()
    _scan_exclude = {'.git', '.svn', 'node_modules', '__pycache__', '.venv', 'venv',
                     'env', '.env', 'dist', 'build', '.eggs', '.tox', '.mypy_cache',
                     '.pytest_cache', '.next', '.nuxt', '.cache', 'site-packages',
                     'vendor', 'third_party'}

    # v4.6.1: 优先用 context 的 walk 缓存（零 I/O），在内存中过滤
    if context is not None and hasattr(context, '_ensure_walk_cache'):
        context._ensure_walk_cache()
    if context is not None and hasattr(context, '_all_walk_cache') and context._all_walk_cache is not None:
        for fpath, rel, f in context._all_walk_cache:
            if not fpath.startswith(project_path):
                continue
            rel_fwd = rel.replace('\\', '/')
            parts = rel_fwd.split('/')[:-1]
            skip = False
            for part in parts:
                if part in _scan_exclude or part.startswith('.'):
                    skip = True
                    break
            if skip:
                continue
            if f.endswith('.py') and f != '__init__.py' and not f.startswith('_'):
                modules.add(f[:-3])
            for part in parts:
                if part and not part.startswith('_'):
                    modules.add(part)
        _project_modules_cache[project_path] = modules
        return modules

    # 回退：自行扫描磁盘（context 不可用时）
    try:
        for root, dirs, files in os.walk(project_path):
            dirs[:] = [d for d in dirs if d not in _scan_exclude and not d.startswith('.')]
            # 所有目录名都可能是模块名（namespace package）
            for d in dirs:
                if not d.startswith('_'):
                    modules.add(d)
            # 所有 .py 文件名（去掉扩展名）都是模块名
            for f in files:
                if f.endswith('.py') and f != '__init__.py' and not f.startswith('_'):
                    modules.add(f[:-3])
    except Exception as e:  # noqa: broad exception handling
        pass

    _project_modules_cache[project_path] = modules
    return modules


# ===== 轻量级 Python import 提取器（v4.6.1） =====
# 专门为 AI-SPEC-01 设计：只提取 import 信息，避免 get_ast_summary 的全量分析
# 相比 get_ast_summary 快 5~10 倍（不计算复杂度、函数、类、try 等）

def _extract_py_imports(content: str):
    """从 Python 源码中提取 import 语句，返回 [(pkg_name, lineno)]
    使用 ast 模块的单次遍历，仅关注 Import / ImportFrom 节点。
    """
    try:
        import ast as _ast
        tree = _ast.parse(content)
    except (SyntaxError, ValueError):
        return []

    imports = []
    for node in _ast.walk(tree):
        if isinstance(node, _ast.Import):
            for alias in node.names:
                pkg = alias.name.split('.')[0]
                imports.append((pkg, node.lineno))
        elif isinstance(node, _ast.ImportFrom):
            if node.module and node.level == 0:  # 非相对导入
                pkg = node.module.split('.')[0]
                imports.append((pkg, node.lineno))
    return imports


_pypi_check_time_budget = 10.0  # v2.9.1: max 10s for all PyPI checks
_pypi_check_time_spent = 0.0

_npm_check_time_budget = 10.0  # v4.6.1: npm 检查同样设时间预算，避免网络慢拖死
_npm_check_time_spent = 0.0
_npm_failed = False  # v4.6.1: npm 不可用时标记，后续全部跳过

def _check_pypi_package(package_name: str, timeout: int = 1) -> bool:
    """检查Python包是否存在于PyPI
    网络失败时返回True（降级处理，不报错）
    v2.9.1: 添加时间预算，超过10秒后跳过网络检查
    """
    global _pypi_failed, _pypi_check_time_spent, _pypi_check_time_budget
    
    if _pypi_failed:
        return True  # 网络不可用，假设存在
    
    name_lower = package_name.lower()

    # v4.6.1-2: 预热完成后，不触发任何新的网络请求
    # 所有包名应该已经在预热阶段查过并写入缓存，未命中的也已降级为"存在"
    # 这样规则执行阶段 100% 内存命中，彻底避免卡死和GIL争用
    if _prewarm_done and name_lower not in _pypi_cache:
        return True  # 预热没覆盖到的，降级假设存在

    # v2.9.1: 时间预算用完，降级为"假设存在"
    import time as _time_mod
    if _pypi_check_time_spent >= _pypi_check_time_budget:
        return True

    if name_lower in _pypi_cache:
        return _pypi_cache[name_lower]
    
    # 常见标准库/内置模块白名单
    std_libs = {
        # Python标准库（常用的）
        'os', 'sys', 're', 'json', 'math', 'time', 'datetime', 'collections',
        'itertools', 'functools', 'typing', 'ast', 'inspect', 'importlib',
        'subprocess', 'threading', 'multiprocessing', 'asyncio', 'io',
        'pathlib', 'shutil', 'tempfile', 'hashlib', 'hmac', 'random',
        'statistics', 'argparse', 'logging', 'configparser', 'csv',
        'html', 'http', 'urllib', 'urllib.request', 'urllib.error',
        'urllib.parse', 'xml', 'base64', 'struct', 'socket', 'ssl',
        'email', 'smtplib', 'sqlite3', 'unittest', 'traceback',
        'warnings', 'copy', 'pickle', 'shelve', 'uuid', 'enum',
        'dataclasses', 'abc', 'weakref', 'contextlib', 'glob',
        'fnmatch', 'linecache', 'textwrap', 'string', 'unicodedata',
        'codecs', 'locale', 'gettext', 'platform', 'ctypes',
        'concurrent', 'concurrent.futures', 'queue', 'select',
        'signal', 'atexit', 'gc', 'sysconfig', 'zipfile', 'tarfile',
        'gzip', 'bz2', 'lzma', 'zlib', 'mimetypes',
        # 常见第三方包（非常流行的，避免误报）
        'requests', 'flask', 'django', 'numpy', 'pandas', 'scipy',
        'sqlalchemy', 'pytest', 'setuptools', 'pip', 'wheel',
        'click', 'fastapi', 'uvicorn', 'pydantic', 'starlette',
        'httpx', 'aiohttp', 'beautifulsoup4', 'bs4', 'lxml',
        'jinja2', 'werkzeug', 'itsdangerous', 'markupsafe',
        'celery', 'redis', 'pymysql', 'psycopg2', 'psycopg2-binary',
        'mongodb', 'pymongo', 'boto3', 'botocore', 's3transfer',
        'openpyxl', 'xlrd', 'xlsxwriter', 'pillow', 'opencv-python',
        'matplotlib', 'seaborn', 'plotly', 'scikit-learn', 'sklearn',
        'tensorflow', 'torch', 'pytorch', 'transformers', 'torchvision',
        'langchain', 'openai', 'anthropic', 'cohere', 'tiktoken',
        'python-dotenv', 'dotenv', 'pyyaml', 'yaml', 'toml', 'tomli',
        'rich', 'tqdm', 'colorama', 'termcolor', 'tabulate',
        'pyjwt', 'jwt', 'bcrypt', 'cryptography', 'paramiko',
        'fabric', 'docker', 'kubernetes', 'grpcio', 'protobuf',
        'tenacity', 'retry', 'cachetools', 'fakeredis',
        'moto', 'freezegun', 'responses', 'httpretty',
        'black', 'flake8', 'mypy', 'pylint', 'ruff', 'isort',
        'sphinx', 'mkdocs', 'pdoc', 'coverage', 'codecov',
        'tox', 'nox', 'poetry', 'pipenv', 'virtualenv',
        'schedule', 'apscheduler', 'croniter',
        'python-dateutil', 'dateutil', 'pytz', 'zoneinfo',
        'faker', 'factory_boy', 'hypothesis',
        'gunicorn', 'uwsgi', 'mod_wsgi',
        'tornado', 'sanic', 'bottle', 'pyramid',
        'alembic', 'marshmallow', 'pydantic-settings',
        'sqlmodel', 'databases', 'orm',
        'httpx', 'requests-futures',
        'websockets', 'socket.io',
        'pyzmq', 'zmq',
        'watchdog', 'pyinotify',
        'psutil', 'py-cpuinfo', 'gpustat',
        'humanize', 'parse', 'more-itertools',
    }
    
    if name_lower in std_libs:
        _pypi_cache[name_lower] = True
        return True
    
    # 本地导入（同一个项目内的模块，无法验证）
    if '.' in package_name:
        _pypi_cache[name_lower] = True
        return True
    
    # 标准库子模块
    if any(name_lower.startswith(lib + '.') for lib in std_libs):
        _pypi_cache[name_lower] = True
        return True
    
    # 检查本地已安装的包（跳过网络请求）
    local_pkgs = _get_local_packages()
    if name_lower in local_pkgs:
        _pypi_cache[name_lower] = True
        return True

    global _disk_cache_dirty
    
    # v4.6.1: 多线程网络请求限流
    # 非阻塞尝试获取 _net_lock：获取不到说明已有线程在查网络，直接降级避免并发阻塞
    # 单线程串行时 lock 永远能立即拿到，不影响行为
    if not _net_lock.acquire(blocking=False):
        return True  # 其他线程在查网络，降级：假设存在
    
    try:
        # 双检：拿到锁后再查一次缓存（可能其他线程刚才已经查过了）
        if name_lower in _pypi_cache:
            return _pypi_cache[name_lower]
        
        url = f"https://pypi.org/pypi/{package_name}/json"
        
        try:
            req = urllib.request.Request(url, method='HEAD')
            _t0 = _time_mod.time()
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                _pypi_check_time_spent += (_time_mod.time() - _t0)
                exists = resp.status == 200
                _pypi_cache[name_lower] = exists
                _disk_cache_dirty = True
                return exists
        except urllib.error.HTTPError as e:
            _elapsed = _time_mod.time() - _t0
            _pypi_check_time_spent += _elapsed  # v4.6.1: 用实际耗时，而非固定timeout（404响应可能很慢）
            if e.code == 404:
                _pypi_cache[name_lower] = False
                _disk_cache_dirty = True
                return False
            # 其他HTTP错误，视为存在（降级）
            _pypi_cache[name_lower] = True
            return True
        except Exception as e:  # noqa: broad exception handling
            # 网络错误，标记PyPI不可用
            _pypi_failed = True
            _pypi_cache[name_lower] = True  # 降级处理
            return True
    finally:
        _net_lock.release()


def _check_npm_package(package_name: str, timeout: int = 1) -> bool:
    """检查JS包是否存在于npm registry
    网络失败时返回True（降级处理，不报错）
    v4.6.1: 增加时间预算和失败标记，与 PyPI 一致，避免网络慢拖死
    """
    global _npm_failed, _npm_check_time_spent, _npm_check_time_budget
    
    if _npm_failed:
        return True
    
    name_lower = package_name.lower()

    # v4.6.1-2: 预热完成后不触发新网络请求
    if _prewarm_done and name_lower not in _npm_cache:
        return True  # 预热没覆盖到的，降级假设存在

    # 时间预算用完，降级为"假设存在"
    import time as _time_mod
    if _npm_check_time_spent >= _npm_check_time_budget:
        return True

    if name_lower in _npm_cache:
        return _npm_cache[name_lower]
    
    # Node.js内置模块白名单
    node_builtins = {
        'fs', 'path', 'os', 'http', 'https', 'url', 'util', 'events',
        'stream', 'buffer', 'crypto', 'zlib', 'net', 'dgram', 'dns',
        'child_process', 'cluster', 'tls', 'assert', 'console',
        'process', 'querystring', 'string_decoder', 'timers',
        'tty', 'vm', 'readline', 'repl', 'module', 'domain',
        'constants', 'punycode', 'sys',
        # 极常见的npm包
        'react', 'react-dom', 'vue', 'angular', 'svelte',
        'express', 'koa', 'next', 'next.js', 'nuxt',
        'typescript', 'javascript', 'webpack', 'vite', 'rollup',
        'eslint', 'prettier', 'jest', 'mocha', 'chai',
        'axios', 'lodash', 'moment', 'dayjs', 'date-fns',
        'react-router-dom', 'vue-router', 'redux', 'vuex',
        'tailwindcss', 'bootstrap', 'antd', 'element-ui',
        'jquery', 'backbone', 'underscore', 'ramda',
        'mongodb', 'mongoose', 'mysql', 'pg', 'sequelize',
        'typeorm', 'prisma', 'redis', 'ioredis',
        'node-fetch', 'isomorphic-fetch', 'whatwg-fetch',
        'cheerio', 'puppeteer', 'playwright',
        'jsonwebtoken', 'jwt-simple', 'bcrypt',
        'dotenv', 'commander', 'yargs', 'chalk',
        'nodemailer', 'socket.io', 'ws',
        'uuid', 'nanoid', 'shortid',
        'formidable', 'multer', 'body-parser',
        'cookie-parser', 'cors', 'helmet',
        'compression', 'morgan', 'winston', 'pino',
        'pm2', 'forever', 'nodemon',
        '@types/node', '@types/react', '@types/react-dom',
    }
    
    if name_lower in node_builtins:
        _npm_cache[name_lower] = True
        return True
    
    # 相对路径导入（./ ../）
    if package_name.startswith(('.', '..', '/')):
        _npm_cache[name_lower] = True
        return True
    
    # @scope/package 形式
    if package_name.startswith('@') and '/' in package_name:
        _npm_cache[name_lower] = True
        return True
    
    global _disk_cache_dirty
    
    # v4.6.1: 多线程网络请求限流（同 PyPI，共用 _net_lock，两个 registry 串行不并发）
    if not _net_lock.acquire(blocking=False):
        return True
    
    try:
        # 双检
        if name_lower in _npm_cache:
            return _npm_cache[name_lower]
        
        url = f"https://registry.npmjs.org/{package_name}"
        
        try:
            req = urllib.request.Request(url, method='HEAD')
            _t0 = _time_mod.time()
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                _npm_check_time_spent += (_time_mod.time() - _t0)
                exists = resp.status == 200
                _npm_cache[name_lower] = exists
                _disk_cache_dirty = True
                return exists
        except urllib.error.HTTPError as e:
            _npm_check_time_spent += timeout  # Count timeout toward budget
            if e.code == 404:
                _npm_cache[name_lower] = False
                _disk_cache_dirty = True
                return False
            _npm_cache[name_lower] = True
            return True
        except Exception as e:  # noqa: broad exception handling
            # 网络错误，标记npm不可用
            _npm_failed = True
            _npm_cache[name_lower] = True  # 降级处理
            return True
    finally:
        _net_lock.release()


# ===== AI-SPEC-01 幻觉依赖检测 =====
def check_ai_spec_01_hallucinated_deps(context) -> List[Dict]:
    """AI-SPEC-01 幻觉依赖检测
    检测import的包在PyPI/npm不存在（AI瞎编的包名）
    最具差异化的AI代码特征

    v3.4: JS导入检测改用AST(@babel/parser)，精准识别import/require语句，
         不再误匹配字符串中的import/require关键字。
    v4.6.1: 性能优化 - 轻量级import提取、复用context walk缓存、
           懒加载磁盘缓存、合并get_filtered_files调用。
    """
    global _disk_cache_dirty, _pypi_initialized, _npm_initialized
    results = []

    # 检查是否开启了幻觉依赖检测（先判断配置，避免不必要的初始化开销）
    ai_config = context.config.get('ai_code_check', {})
    if not ai_config.get('hallucination_deps_check', True):
        return results

    # v4.6.1: 从磁盘缓存加载（首次调用时才加载，避免每次调用都读磁盘）
    if not _pypi_initialized:
        _init_pypi_cache_from_disk()
        _pypi_initialized = True
    if not _npm_initialized:
        _init_npm_cache_from_disk()
        _npm_initialized = True

    # v4.6.1: 只调用一次 get_filtered_files，避免重复过滤
    all_filtered = context.get_filtered_files("performance")
    py_files = []
    js_files = []
    for f in all_filtered:
        if f.endswith(".py") and os.path.basename(f) != "__init__.py":
            py_files.append(f)
        elif f.endswith((".js", ".ts", ".jsx", ".tsx")):
            js_files.append(f)

    if not py_files and not js_files:
        return results

    # v2.9.1: 大项目限制文件数，避免网络请求超时
    if len(py_files) + len(js_files) > 100:
        py_files = py_files[:80]
        js_files = js_files[:20]

    all_issues = []
    # 预先确定项目根路径，避免循环中重复计算
    _base_path = context.project_path or context.backend_path or "."

    # ===== Python 导入检测（复用 context AST 摘要缓存，零额外解析开销）=====
    # v4.6.1 修正：_extract_py_imports 每次都 ast.parse，200+ 文件反而比 get_ast_summary 还慢
    # 因为 prefetch_ast_summary 已经预热过所有 AST，直接复用缓存零开销
    _project_modules = _get_project_modules(context.project_path, context=context)
    if context.backend_path and context.backend_path != context.project_path:
        _project_modules |= _get_project_modules(context.backend_path, context=context)

    for fpath in py_files:
        content = context.safe_read(fpath)
        if not content:
            continue

        rel = os.path.relpath(fpath, _base_path)

        # 直接复用 AST 摘要缓存（prefetch_ast_summary 已预热）
        _sum = context.get_ast_summary(fpath)
        if not _sum:
            continue
        raw_imports = _sum.get('imports', [])
        if not raw_imports:
            continue

        # v4.6.1: 惰性计算 lines，只有当发现问题时才 split（大多数文件没有问题）
        lines = None
        imported_packages = set()

        for _imp in raw_imports:
            _type = _imp.get('type', 'import')
            lineno = _imp.get('lineno', 0)
            if _type == 'import':
                pkg = _imp['module'].split('.')[0]
                imported_packages.add((pkg, lineno))
            elif _type == 'from_import':
                if _imp.get('module') and _imp.get('level', 0) == 0:
                    pkg = _imp['module'].split('.')[0]
                    imported_packages.add((pkg, lineno))

        for pkg_name, lineno in imported_packages:
            # 跳过本项目内的模块（使用预计算缓存，避免逐文件isfile/isdir）
            if pkg_name in _project_modules:
                continue

            # 检查PyPI
            if not _check_pypi_package(pkg_name):
                if lines is None:
                    lines = content.split('\n')
                all_issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': lineno,
                    'desc': f'Python包 "{pkg_name}" 在PyPI不存在（疑似AI幻觉生成）',
                    'snippet': lines[lineno - 1].strip() if lineno - 1 < len(lines) else "",
                    'pkg': pkg_name,
                })

    # ===== JS/TS 导入检测（纯正则实现，v4.6.1 砍掉 Node AST 避免死锁）=====
    if js_files:
        import_pattern = re.compile(
            r'^\s*import\s+(?:.+\s+from\s+)?["\']([^"\']+)["\']',
            re.MULTILINE
        )
        require_pattern = re.compile(
            r'(?<!\w)require\s*\(\s*["\']([^"\']+)["\']',
            re.MULTILINE
        )

    for fpath in js_files:
        content = context.safe_read(fpath)
        if not content:
            continue

        rel = os.path.relpath(fpath, _base_path)
        # v4.6.1: 惰性计算 lines（只有发现问题时才 split）
        lines = None

        imported_packages = set()
        for m in import_pattern.finditer(content):
            imported_packages.add((m.group(1), m.start()))
        for m in require_pattern.finditer(content):
            imported_packages.add((m.group(1), m.start()))

        for pkg, match_start in imported_packages:
            if pkg.startswith(('.', '..', '/')):
                continue

            if pkg.startswith('@'):
                parts = pkg.split('/')
                if len(parts) >= 2:
                    pkg_name = '/'.join(parts[:2])
                else:
                    pkg_name = pkg
            else:
                pkg_name = pkg.split('/')[0]

            line_num = content[:match_start].count('\n') + 1

            local_pkg = os.path.join(
                os.path.dirname(fpath), 'node_modules', pkg_name
            )
            if os.path.isdir(local_pkg):
                continue

            if not _check_npm_package(pkg_name):
                if lines is None:
                    lines = content.split('\n')
                all_issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': line_num,
                    'desc': f'JS包 "{pkg_name}" 在npm不存在（疑似AI幻觉生成）',
                    'snippet': lines[line_num - 1].strip() if line_num - 1 < len(lines) else "",
                    'pkg': pkg_name,
                })
    
    if all_issues:
        total = len(all_issues)
        detail_lines = [
            f"{issue['rel']}:{issue['line']} - {issue['desc']}"
            for issue in all_issues[:15]
        ]
        
        network_note = ""
        if _pypi_failed:
            network_note = "\n\n⚠️ 注意：PyPI API连接失败，Python幻觉检测已降级（不影响其他规则）"
        
        results.append({
            'id': 'AI-SPEC-01',
            'name': '幻觉依赖检测',
            'level': 'error',
            'message': f'发现 {total} 个疑似AI幻觉生成的不存在依赖包',
            'detail': '\n'.join(detail_lines) + network_note,
            'file': all_issues[0]['file'] if all_issues else '',
            'line': all_issues[0]['line'] if all_issues else 0,
            'snippet': all_issues[0]['snippet'] if all_issues else '',
            'fix': '核实包名是否正确，这些包在官方包仓库中不存在，可能是AI凭空编造的',
            'category': 'ai_specific',
            'suggestion_code': '# 核实步骤：\n# 1. 在 https://pypi.org 或 https://npmjs.com 搜索包名\n# 2. 如果不存在，用正确的替代包：\n\n# Python示例：\n# 错误：import non_existent_pkg\n# 正确：import real_package  # pip install real_package\n\n# JS示例：\n// 错误：const fake = require("ai-fake-lib");\n// 正确：const real = require("real-lib");  // npm install real-lib',
        })
    
    # 将新增的缓存结果持久化到磁盘
    _flush_pypi_cache_to_disk()
    _flush_npm_cache_to_disk()
    
    return results


# ===== 预热接口（供 runner 在规则执行前单线程调用，避免多线程争抢）=====

def prewarm_hallucination_caches(context=None):
    """预热幻觉依赖检测的所有缓存（PyPI、NPM、本地包列表）。
    
    v4.6.1: 多线程并发下，多条AI规则同时首次触发缓存初始化会产生
    磁盘I/O争抢（每个线程都去读 pypi_cache.json + importlib.metadata）。
    在规则执行前单线程提前预热，避免并发阻塞。
    
    v4.6.1-2: 如果传入 context，进一步预查项目中所有 import 的包名。
    这样规则执行时 100% 内存命中，零网络请求，彻底解决卡死问题。
    未命中的包会被标记为「假设存在」，规则执行时不触发网络查询。
    """
    _init_pypi_cache_from_disk()
    _init_npm_cache_from_disk()
    _ = _get_local_packages()

    if context is None:
        return
    
    # 收集项目中所有 import 的包名，预查一遍
    # 单线程 + 网络失败快速降级，总预算 10 秒
    import time as _t
    budget_start = _t.time()
    BUDGET = 10.0  # 最多花10秒预查
    
    # 收集 Python import
    py_pkgs = set()
    js_pkgs = set()
    
    try:
        all_files = context.get_filtered_files("performance")
        for fpath in all_files:
            if fpath.endswith(".py") and os.path.basename(fpath) != "__init__.py":
                _sum = context.get_ast_summary(fpath)
                if not _sum:
                    continue
                for _imp in _sum.get('imports', []):
                    if _imp.get('level', 0) > 0:
                        continue  # 相对导入跳过
                    mod = _imp.get('module', '')
                    if mod:
                        pkg = mod.split('.')[0]
                        py_pkgs.add(pkg)
            elif fpath.endswith((".js", ".ts", ".jsx", ".tsx")):
                # JS 文件简单正则扫 import/require（不依赖 AST analyzer）
                content = context.safe_read(fpath)
                if not content:
                    continue
                # import xxx from 'pkg' / const x = require('pkg')
                import re as _re
                for m in _re.finditer(r"""(?:import\s+(?:.+?from\s+)?['"]([^'"]+)['"]|require\(\s*['"]([^'"]+)['"]\s*\))""", content):
                    pkg = m.group(1) or m.group(2)
                    if pkg and not pkg.startswith(('.', '/', '@/')):
                        # @scope/pkg 保留完整名
                        base = pkg.split('/')[0] if not pkg.startswith('@') else '/'.join(pkg.split('/')[:2])
                        js_pkgs.add(base)
    except Exception:
        pass
    
    # 单线程逐个查，严格控制时间预算
    for pkg in list(py_pkgs):
        if _t.time() - budget_start >= BUDGET:
            break
        # 已经在缓存里的跳过
        if pkg.lower() in _pypi_cache:
            continue
        _check_pypi_package(pkg, timeout=2)
    
    for pkg in list(js_pkgs):
        if _t.time() - budget_start >= BUDGET:
            break
        if pkg.lower() in _npm_cache:
            continue
        _check_npm_package(pkg, timeout=2)
    
    # 剩余没查到的，全部标记为存在（降级），避免规则执行时再查
    for pkg in py_pkgs:
        if pkg.lower() not in _pypi_cache:
            _pypi_cache[pkg.lower()] = True
    for pkg in js_pkgs:
        if pkg.lower() not in _npm_cache:
            _npm_cache[pkg.lower()] = True
    
    # 持久化新查到的
    _flush_pypi_cache_to_disk()
    _flush_npm_cache_to_disk()
    
    # 标记预热完成，规则执行阶段不再触发任何网络请求
    global _prewarm_done
    _prewarm_done = True


# ===== AI-SPEC-02 占位符残留 =====


# ===== 规则定义列表 =====
RULES = [
    {
        'id': 'AI-SPEC-01',
        'name': '幻觉依赖检测',
        'level': 'blocking',
        'category': 'ai_code_check',
        'module_id': 'ai_specific',
        'applicable_types': [],
        'description': '检测import的包在PyPI/npm不存在（AI瞎编的包名），JS检测使用AST增强',
        'check': check_ai_spec_01_hallucinated_deps,
    },
]
