"""AI专项质量规则 - 占位符残留检测
从 ai_specific_rules.py 拆分而来，包含占位符残留检测规则（AI-SPEC-02）
"""

"""
智能质检 - P0 特有问题检测规则 (v3.4 AST增强版)
最具差异化的AI增强检测能力，传统Linter难以覆盖的问题

v3.4 改进: JS检查全部改用AST解析(@babel/parser)，消除正则误报。
           Python检查保持原有ast模块实现。

AI-SPEC-01: 幻觉依赖检测 - import的包在pypi/npm不存在（AI瞎编的包名）
AI-SPEC-02: 占位符残留 - TODO: implement、空函数体等AI生成的占位代码
AI-SPEC-03: 调试代码残留 - console.log、print()、debugger 留在生产代码
AI-SPEC-04: AI生成标记 - // Generated by ChatGPT 这类来源标注
"""

import re
import os
import ast
import json
import time as _time
import urllib.request
import urllib.error
from typing import List, Dict, Any, Set

# 从 hallucination.py 导入共享的 AST 分析器初始化函数
try:
    from .hallucination import _get_ast_analyzer
except ImportError:
    def _get_ast_analyzer():
        return None

# 尝试导入AST分析器（延迟初始化，避免import时阻塞）
_ast_analyzer = None
_ast_available = None  # None = 未检查，True/False = 已检查


# ===== AI-SPEC-02 占位符残留 =====
def check_ai_spec_02_placeholder_remnants(context) -> List[Dict]:
    """AI-SPEC-02 占位符残留检测
    AI生成代码常见：TODO占位符+空函数体、未实现标记
    误报控制：只检测空函数+TODO组合，不单独标记普通TODO注释
    
    v3.4: JS空函数检测改用AST，精准识别空函数体（只有{}或只有return），
         不再误匹配字符串中的函数模式。
    """
    results = []
    
    py_files = [f for f in context.get_filtered_files("performance")
                if f.endswith(".py") and os.path.basename(f) != "__init__.py"]
    js_files = [f for f in context.get_filtered_files("performance") if f.endswith((".js", ".ts", ".jsx", ".tsx"))]
    
    if not py_files and not js_files:
        return results
    
    all_issues = []
    
    # AI生成的典型占位模式（高置信度，AI特有）
    placeholder_patterns = [
        (r'(?:throw|raise)\s+[\'"](?:Not implemented|未实现|not yet implemented)[\'"]',
         '未实现异常抛出（占位代码）'),
    ]
    
    def check_empty_function_py(fpath: str, content: str, lines: list, rel: str):
        """检测Python中空函数体 + TODO注释组合（AI占位代码特征）"""
        try:
            issues = []
            tree = context.parse_ast(fpath)
            if tree is None:
                return issues
            
            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                
                body = node.body
                if not body:
                    continue
                
                is_empty = False
                
                if len(body) == 1 and isinstance(body[0], ast.Pass):
                    is_empty = True
                elif (len(body) == 1 and isinstance(body[0], ast.Expr) and 
                      isinstance(body[0].value, ast.Constant) and
                      isinstance(body[0].value.value, str)):
                    continue  # 纯docstring的函数不标记
                elif len(body) == 1 and isinstance(body[0], ast.Return):
                    ret = body[0]
                    if ret.value is None or (isinstance(ret.value, ast.Constant) and ret.value.value is None):
                        is_empty = True
                
                if not is_empty:
                    continue
                
                lineno = node.lineno
                has_placeholder_marker = False
                
                start = max(0, lineno - 2)
                end = min(len(lines), lineno + len(body) + 2)
                for i in range(start, end):
                    line_lower = lines[i].lower()
                    if any(marker in line_lower for marker in 
                           ['todo', 'fixme', 'not implemented', 'not yet', 
                            'implement', 'placeholder', '占位', '未实现']):
                        has_placeholder_marker = True
                        break
                
                if has_placeholder_marker:
                    issues.append({
                        'file': fpath,
                        'rel': rel,
                        'line': lineno,
                        'desc': f'空函数 "{node.name}" + TODO标记（AI生成占位代码）',
                        'snippet': lines[lineno - 1].strip() if lineno - 1 < len(lines) else "",
                    })
            
            return issues
        except SyntaxError:
            return []
    
    def check_empty_function_js_ast(fpath: str, content: str, lines: list, rel: str):
        """v3.4: AST方式检测JS空函数体 + TODO标记"""
        issues = []
        
        _analyzer = _get_ast_analyzer()
        if not _analyzer:
            return None  # AST不可用，调用方降级到正则
        ast_empty = _analyzer.get_js_empty_functions(fpath)
        if ast_empty is None:
            return None  # AST不可用，调用方降级到正则
        
        for ef in ast_empty:
            name = ef.get("name", "anonymous")
            line_num = ef.get("line", 0)
            issues.append({
                'file': fpath,
                'rel': rel,
                'line': line_num,
                'desc': f'空函数 "{name}" + TODO标记（AI生成占位代码）',
                'snippet': lines[line_num - 1].strip() if line_num - 1 < len(lines) else "",
            })
        
        return issues
    
    def check_empty_function_js_regex(fpath: str, content: str, lines: list, rel: str):
        """正则方式检测JS空函数体（降级用）"""
        issues = []
        
        empty_func_pattern = re.compile(
            r'(?:function\s+(\w+)\s*\([^)]*\)\s*\{\s*\}|'
            r'(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s+)?\([^)]*\)\s*=>\s*\{\s*\})',
            re.MULTILINE
        )
        
        for m in empty_func_pattern.finditer(content):
            func_name = m.group(1) or m.group(2) or 'anonymous'
            line_num = content[:m.start()].count('\n') + 1
            
            has_todo = False
            for i in range(max(0, line_num - 2), min(len(lines), line_num + 2)):
                if any(marker in lines[i].lower() for marker in 
                       ['todo', 'fixme', 'not implemented', 'implement', '占位', '未实现']):
                    has_todo = True
                    break
            
            if has_todo:
                issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': line_num,
                    'desc': f'空函数 "{func_name}" + TODO标记（AI生成占位代码）',
                    'snippet': lines[line_num - 1].strip() if line_num - 1 < len(lines) else "",
                })
        
        return issues
    
    # ===== Python 文件检测 =====
    for fpath in py_files:
        content = context.safe_read(fpath)
        if not content:
            continue
        
        lines = content.split('\n')
        rel = os.path.relpath(fpath, context.project_path or context.backend_path or ".")
        basename = os.path.basename(fpath)
        
        if basename.startswith('test_') or basename.startswith('__'):
            continue
        
        for pat, desc in placeholder_patterns:
            for m in re.finditer(pat, content, re.IGNORECASE):
                line_num = content[:m.start()].count('\n') + 1
                all_issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': line_num,
                    'desc': desc,
                    'snippet': lines[line_num - 1].strip() if line_num - 1 < len(lines) else "",
                })
        
        all_issues.extend(check_empty_function_py(fpath, content, lines, rel))
    
    # ===== JS/TS 文件检测 =====
    for fpath in js_files:
        content = context.safe_read(fpath)
        if not content:
            continue
        
        lines = content.split('\n')
        rel = os.path.relpath(fpath, context.project_path or context.backend_path or ".")
        basename = os.path.basename(fpath)
        
        if any(x in basename.lower() for x in ['.test.', '.spec.', 'test.']):
            continue
        
        for pat, desc in placeholder_patterns:
            for m in re.finditer(pat, content, re.IGNORECASE):
                line_num = content[:m.start()].count('\n') + 1
                all_issues.append({
                    'file': fpath,
                    'rel': rel,
                    'line': line_num,
                    'desc': desc,
                    'snippet': lines[line_num - 1].strip() if line_num - 1 < len(lines) else "",
                })
        
        # v3.4: 优先AST，降级正则
        _analyzer = _get_ast_analyzer()
        if _analyzer:
            ast_result = check_empty_function_js_ast(fpath, content, lines, rel)
            if ast_result is not None:
                all_issues.extend(ast_result)
                continue
        # 降级到正则
        all_issues.extend(check_empty_function_js_regex(fpath, content, lines, rel))
    
    if all_issues:
        total = len(all_issues)
        detail_lines = [
            f"{issue['rel']}:{issue['line']} - {issue['desc']}"
            for issue in all_issues[:15]
        ]
        
        results.append({
            'id': 'AI-SPEC-02',
            'name': '占位符残留检测',
            'level': 'error',
            'message': f'发现 {total} 处AI生成代码占位符残留',
            'detail': '\n'.join(detail_lines),
            'file': all_issues[0]['file'] if all_issues else '',
            'line': all_issues[0]['line'] if all_issues else 0,
            'snippet': all_issues[0]['snippet'] if all_issues else '',
            'fix': '补充完整的实现逻辑，或删除未使用的占位代码',
            'category': 'ai_specific',
            'suggestion_code': '// 错误：空函数+TODO占位符\nfunction processData(data) {\n  // TODO: implement\n}\n\n// 正确：补充实现逻辑\nfunction processData(data) {\n  if (!data) return [];\n  return data.map(item => ({\n    id: item.id,\n    name: item.name,\n    processed: true,\n  }));\n}\n\n// 或者：如果确实暂未实现，抛出明确错误\nfunction processData(data) {\n  throw new Error("processData 尚未实现");\n}',
        })
    
    return results


# ===== AI-SPEC-03 调试代码残留 =====


# ===== 规则定义列表 =====
RULES = [
    {
        'id': 'AI-SPEC-02',
        'name': '占位符残留检测',
        'level': 'blocking',
        'category': 'ai_code_check',
        'module_id': 'ai_specific',
        'applicable_types': [],
        'description': '检测TODO占位符、空函数体、未实现标记等AI生成的占位代码，JS检测使用AST增强',
        'check': check_ai_spec_02_placeholder_remnants,
    },
]
